In [2]:
from IPython.display import Image
%matplotlib inline
import pandas as pd
from io import StringIO
import sys

In [3]:
csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

In [4]:
df = pd.read_csv(StringIO(csv_data))

In [5]:
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [6]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [7]:
df.dropna(axis = 0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [8]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [12]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [13]:
df.dropna(axis = 1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [14]:
df.dropna(how = 'all')

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [15]:
df.dropna(subset = ['C'])

      A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

In [17]:
df.dropna(thresh=4)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [19]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [20]:
from sklearn.impute import SimpleImputer
import numpy as np

In [21]:
imr = SimpleImputer(missing_values=np.nan, strategy='mean')

In [22]:
imr = imr.fit(df.values)

In [23]:
imputed_data = imr.transform(df.values)

In [24]:
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [25]:
df.fillna(df.mean)

,A,B,C,D
0,1.0,2.0,3.0,4.0
1,5.0,6.0,<bound method DataFrame.mean of A B ...,8.0
2,10.0,11.0,12.0,<bound method DataFrame.mean of A B ...

In [26]:
#new data frame

In [27]:
import pandas as pd

In [47]:
df = pd.DataFrame([
['green', 'XL', 10.1, 'class2'],
['red', 'L', 13.5, 'class1'],
['blue', 'M', 15.3, 'class2']])

In [48]:
df.columns = ['color', 'size', 'price', 'classlabel']

In [49]:
df

   color size  price classlabel
0  green   XL   10.1     class2
1    red    L   13.5     class1
2   blue    M   15.3     class2

In [31]:
#nominal feature = color, ordinary feature = size, numerical = price

In [35]:
#string to integer

In [50]:
size_mapping = {
'XL' : 3, 
'L': 2,
'M' : 1
}

In [51]:
df['size'] = df['size'].map(size_mapping)

In [52]:
df

   color  size  price classlabel
0  green     3   10.1     class2
1    red     2   13.5     class1
2   blue     1   15.3     class2

In [53]:
#from integer to string reverse

In [54]:
inv_size_mapping = {v : k for k, v in size_mapping.items()}

In [55]:
df['size'].map(inv_size_mapping)

0    XL
1     L
2     M
Name: size, dtype: object

In [56]:
import numpy as np

In [57]:
class_mapping = {label : idx for idx, label in enumerate(np.unique(df['classlabel'])) }

In [58]:
class_mapping

{'class1': 0, 'class2': 1}

In [60]:
df['classlabel'] = df['classlabel'].map(class_mapping)

In [61]:
df

   color  size  price  classlabel
0  green     3   10.1           1
1    red     2   13.5           0
2   blue     1   15.3           1

In [62]:
#reverse int class label to string

In [63]:
inv_class_mapping = {v : k for k, v in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inv_class_mapping)

In [64]:
df

   color  size  price classlabel
0  green     3   10.1     class2
1    red     2   13.5     class1
2   blue     1   15.3     class2

In [67]:
from sklearn.preprocessing import LabelEncoder

In [69]:
class_le = LabelEncoder()

In [71]:
y = class_le.fit_transform(df['classlabel'].values)

In [72]:
y

array([1, 0, 1])

In [77]:
df.classlabel

0    class2
1    class1
2    class2
Name: classlabel, dtype: object

In [80]:
df

   color  size  price classlabel
0  green     3   10.1     class2
1    red     2   13.5     class1
2   blue     1   15.3     class2

In [78]:
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

In [79]:
df

   color  size  price classlabel
0  green     3   10.1     class2
1    red     2   13.5     class1
2   blue     1   15.3     class2

In [81]:
X = df[['color', 'size', 'price']].values

In [83]:
color_le = LabelEncoder()

In [90]:
X[:, 0]= color_le.fit_transform(X[:, 0])

In [91]:
X

array([[1, 3, 10.1],
       [2, 2, 13.5],
       [0, 1, 15.3]], dtype=object)

In [92]:
df

   color  size  price classlabel
0  green     3   10.1     class2
1    red     2   13.5     class1
2   blue     1   15.3     class2

In [94]:
from sklearn.preprocessing import OneHotEncoder

In [96]:
X = df[['color', 'size', 'price']].values

In [97]:
color_ohe = OneHotEncoder()

In [98]:
color_ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [99]:
from sklearn.compose import ColumnTransformer

In [101]:
X = df[['color', 'size', 'price']].values

In [102]:
c_transf = ColumnTransformer([('onehot', OneHotEncoder(), [0]),
                              ('nothing', 'passthrough', [1, 2])])

c_transf.fit_transform(X).astype(float)

array([[ 0. ,  1. ,  0. ,  3. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  1. , 15.3]])

In [103]:
pd.get_dummies(df[['price', 'color', 'size']])

   price  size  color_blue  color_green  color_red
0   10.1     3       False         True      False
1   13.5     2       False        False       True
2   15.3     1        True        False      False

In [104]:
pd.get_dummies(df[['price', 'color', 'size']], drop_first=True)

   price  size  color_green  color_red
0   10.1     3         True      False
1   13.5     2        False       True
2   15.3     1        False      False

In [105]:
comor_ohe = OneHotEncoder(categories='auto', drop = 'first')
c_transf = ColumnTransformer([('onehot', color_ohe, [0]), 
                             ('nothing', 'passthrough', [1, 2])])

c_transf.fit_transform(X).astype(float)

array([[ 0. ,  1. ,  0. ,  3. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  1. , 15.3]])

In [106]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/'
'ml/machine-learning-databases/wine/wine.data',
header=None)

In [108]:
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
'Alcalinity of ash', 'Magnesium', 'Total phenols',
'Flavanoids', 'Nonflavanoid phenols',
'Proanthocyanins',
'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
'Proline']

In [109]:
print('Class labels:', np.unique(df_wine['Class label']))

Class labels: [1 2 3]

In [110]:
df_wine.head()

,Class label,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [111]:
from sklearn.model_selection import train_test_split

In [116]:
X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [117]:
from sklearn.preprocessing import MinMaxScaler

In [118]:
mms = MinMaxScaler()

In [119]:
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [123]:
from sklearn.preprocessing import StandardScaler

In [124]:
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [126]:
#test norma and standard

In [127]:
ex = np.array([0, 1, 2, 3, 4, 5])
print('standarized:', (ex - ex.mean()) / ex.std())
#normalize
print('normalized', (ex - ex.min()) / (ex.max() - ex.min()))
23.

standarized: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
normalized [0.  0.2 0.4 0.6 0.8 1. ]

23.0